tokenGen:
  port : 8080
  host : "tokens"
  #host: "localhost"
  timeout: 10000000000 #10s
  retry: 10
  timeoutRetry:  300000000 #3s

srv: 
  maxHeaderBytes: 1048576  
  readTimeout: 10000000000   #seconds * time 
  writeTimeout: 10000000000  
  readHeaderTimeout: 10000000000
  timeOutSec: 10 # 10s     
  port: "8080"          
  host: "0.0.0.0" 

mysql:
  username: "mysql"
  host: "mysql"
  #host: "localhost"
  port: "3306" #"3309" #"3306"
  dbname: "mysql" 
  options: "charset=utf8mb4&parseTime=True&loc=Local"
  connMaxLifetime: 180000000000 #minute * time
  maxOpenConns: 10  
  maxIdleConns: 10 
  retry: 10
  timeWaitPerTry : 3000000000 #3s

product:
  #pathToCheckDir: "D:\\Projects\\Go\\shop_work\\user_orders\\user_orders\\tmp"
  #pathToTemplate: "D:\\Projects\\Go\\shop_work\\user_orders\\user_orders\\tmp"
  pathToCheckDir: "./tmp"
  pathToTemplate: "./templates"
  templateName: "template.pdf"
  fontName: "wts11"
  fontFileName: "wts11.ttf"
  timeFormat: "2006_01_02-15_04_05"
  templateW: 209.9
  templateH : 148.2